name: Update Hosts

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-neo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Update Scripts in Parallel
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/lepasid/extra-neocities-org.git"

        ./touch.sh

        ./runner-1.sh &
        ./runner-2.sh &
        ./runner-3.sh &
        ./runner-4.sh &
        ./runner-5.sh &
        ./runner-6.sh &
        ./runner-7.sh &
        ./runner-8.sh &
        ./runner-9.sh &
        ./runner-10.sh &
        ./runner-11.sh &
        ./runner-12.sh &

        wait

        git rm -f hosts
        ./merge.sh
        ./sort.sh

        git add hosts
        git commit -m "Update hosts"
        git push origin HEAD:main