name: Update Neo

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  update-neo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Update Script
      run: |
        ./update_neo.sh
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        git remote set-url origin https://$GH_TOKEN@github.com/MeFinity/Neocities-Host.git

        git add neohosts.txt
        git commit -m "Update Neo hosts file"
        git push origin HEAD:main